
namespace VizorLibs.MessageTypes
{
    public class ROSMessageTrajectory : ROSMessage
    {
        new public RobotTrajectoryMsg msg { get; set; }
    }

    public class ROSMessagePlannedTrajectory : ROSMessage // deprecated
    {
        new public PlannedTrajectoryMsg msg { get; set; }
    }

    /// <summary>
    /// Robot trajectory including the trajectory mesh
    /// </summary>

    public class RobotTrajectoryMsg
    {
        public string platform_name { get; set; }
        public BuiltInMsg.JointTrajectoryMsg joint_trajectory { get; set; }
        public BuiltInMsg.MeshMsg mesh_trajectory { get; set; }

        public RobotTrajectoryMsg(string platform_name, BuiltInMsg.JointTrajectoryMsg joint_trajectory, BuiltInMsg.MeshMsg mesh_trajectory)
        {
            this.platform_name = platform_name;
            this.joint_trajectory = joint_trajectory; // degrees, not radians!
            this.mesh_trajectory = mesh_trajectory;
        }
    }

    /// <summary>
    /// Robot trajectory generated by MoveIt
    /// </summary>
    public class PlannedTrajectoryMsg
    {
        public string name { get; set; }
        public string platform_name { get; set; }
        public BuiltInMsg.JointTrajectoryMsg joint_trajectory { get; set; }

        public PlannedTrajectoryMsg(string name, string platform_name, BuiltInMsg.JointTrajectoryMsg joint_trajectory)
        {
            this.name = name;
            this.platform_name = platform_name;
            this.joint_trajectory = joint_trajectory; // degrees, not radians!
        }
    }
}
